### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Dhy19971** [thenick775/gbajs3#137]
I literally follow the instructions you indicated to start the docker, leaving the entire configuration as default. I'm getting this error. Where am I wrong?

`nginx: [emerg] host not found in upstream "gba-auth-server:443" in /etc/nginx/conf.d/nginx.conf:6 webserver-1 exited with code`

**Comment by thenick775** [comment]
Can you put your full docker compose output here along with a `tree` command of your file structure? `ls -R .` would also be helpful!

But what this means is that the auth server failed to start, most likely due to ssl certificate placement.

Since the web server is dependent on the auth server, it failed to start as well.

**Comment by thenick775** [comment]
Happy to rectify the README if there's something missing 😎

**Comment by thenick775** [comment]
I've made some updates to the README startup section, let me know if this helps you!

I'll be wrapping all of these instructions into an interactive script soon as well for convenience.

Feel free to keep posting here, happy to help get you setup!

**Comment by Dhy19971** [comment]
I think my problem is the doors. How can I use another 80/443 instead?

**Comment by Dhy19971** [comment]
I solved my problem by changing the host ulr and specifying the port and changing the port in docker compose
