### ISSUE TITLE
Help me to BUID

### ISSUE THREAD

**Issue by sonht0555** [thenick775/gbajs3#51]
I'm not proficient in TS, I'm familiar with JS. Currently I'm trying to build your repo to make it easier to edit the JS, but it's being minified and encrypted. How can I keep the output files unencrypted when I build

**Comment by sonht0555** [comment]
and I'm also working on a mgba emulator running through wasm, it loses sound when running in the background or switching apps. I saw you solved it by re-enabling the sound, but you wrote it in TS which made it difficult for me to read. Can you rewrite that fix in JS? Thank you very much

**Comment by sonht0555** [comment]
My main test device is iOS

**Comment by thenick775** [comment]
Hello, I don't plan on supporting vanilla JS in this repo any more than I absolutely have to, and do not plan on rewriting anything in plain javascript.

Happy to dig back into what I did at the time and assist if you have specific questions and have looked through the MRs/commits made here to fix the issues I encountered.

In reference to some of your questions:
- to prevent minification with vite you can add the following to the `vite.config.ts` under the `build` object:
```
build: {
  ...
  minify: false,
  ...
},
```
- I am using react, which will obfuscate the javascript after compilation:
   - you may be able to add source maps by adding an environment variable `GENERATE_SOURCEMAP=true` but I am not sure if that will work
   
Feel free to continue asking questions here, but I plan on closing this issue as running `rpm run dev`/`rpm run build`/using the docker container(s) does operate correctly.

**Comment by thenick775** [comment]
@sonht0555 taking a crack at this given I've now seen some of your source code:

You'll need to resume the audio context through SDL2 if your using emscripten for your wasm generated emulator binaries.

I'm using a newer emscripten compiler, so some of the support I have for background audio being resumed in certain situations without me having to do much comes from this compiler update. See my [mGBA fork](https://github.com/thenick775/mgba/tree/feature/wasm) for details on how to build with a newer compiler, and this [dockerfile](https://github.com/thenick775/mgba/blob/feature/wasm/src/platform/wasm/docker/Dockerfile) for concrete details.

From my v1 release, and in certain circumstances you will need to resume the audio context yourself, this must be done within a user gesture such as a tap, keystroke, or button press. You can do this by calling into your module, accessing SDL2, and resume the context yourself:

```
Module.SDL2.audioContext.resume();
```

Here's how I used to do it in plain javascript:
```
// chrome will pause audio due to their autoplay policy changes
// this is a simple way around this, this function will resume the
// audio context and should be used within a user gesture
audioPolyfill(callback = null) {
  if (
	  typeof this.module === 'undefined' ||
	  typeof this.module.SDL2 == 'undefined' ||
	  typeof this.module.SDL2.audioContext == 'undefined'
  )
	  return;

  if (this.module.SDL2.audioContext.state == 'suspended') {
	  this.module.SDL2.audioContext.resume();
  }

  if (this.module.SDL2.audioContext.state == 'running' && callback) {
	  // run user provided callback, usually for removing gesture
	  callback();
  }
}
```

Back in the day, I used an implicit tap on the canvas or a keyboard event to indicate that audio should be resumed if suspended:
```
<script>
	// Work-around chromium autoplay policy
	// https://github.com/emscripten-core/emscripten/issues/6511
	function resumeAudio(e) {
		const audioPolyfillCallback = () => {
			document
				.getElementById('screen')
				.removeEventListener('click', resumeAudio);
			document.removeEventListener('keydown', resumeAudio);
		};
		emulator.AudioPolyfill(audioPolyfillCallback);
	}
	document
		.getElementById('screen')
		.addEventListener('click', resumeAudio);
	document.addEventListener('keydown', resumeAudio);
</script>
```

This would resume the audio using the above javascript when a user clicked or tapped the canvas, or typed any character on the keyboard. 

I though this was pretty unclear and nobody would know this functionality existed, so today what I do is resume the audio if suspended manually when a user adjusts the volume using the volume slider or min/max volume buttons. This way, it's a bit more intuitive what to do if your sound isn't working, given that I have to user a user gesture.

Any other support for audio being resumed after being backgrounded that you see is due to the emscripten compiler update mentioned above in my mGBA fork.

Here's how I do it today, taking into account the audio context states `suspended` for chrome, and `interrupted` for iOS (also taking into account that this method returns a promise):
https://github.com/thenick775/gbajs3/blob/master/gbajs3/src/emulator/mgba/mgba-emulator.tsx#L217

I hope this helps, and I wish you luck with your emulator! 😎

**Comment by sonht0555** [comment]
document.addEventListener("visibilitychange", function() {
	if (document.hidden) {
    Module.SDL2();
	}
});

I have started the sound your way, I will monitor the app's actions, every time it is moved or under the system tray, the above function will be called when it returns.  

Module.SDL2 = () => {
var SDL2 = Module[“SDL2”]
  if (SDL2.audioContext &&    (SDL2.audioContext.state === 'suspended' || SDL2.audioContext.state === 'interrupted')) {
    SDL2.audioContext.resume();
  }
}

I integrated this function straight into mgba.js and called it in the module method.
---
Thank you very much, I also want to try a few other cores besides Mgba, there is also NBA, it is very fast and smooth, VBA is stable and the sound output is good, especially the battery brings high performance, just is a bit less functional. Do you intend to add any new features or functions?

**Comment by sonht0555** [comment]
SkyEmu is also very good, I also talked to Sky. He is an expert in both hardware and software. Very good at OpenGl and Shader Slang. I also see that you intend to use his core. I only know how to reuse the core that has been converted to wasm. I tried reusing SkyEmu's core, but he is compatible with both the interface and the controller. control into wasm, I don't want that so I haven't used it yet

**Comment by thenick775** [comment]
I plan to finalize some other controls, such as rewind support along some other small things.

On the whole this emulator was created to be easy to use once installed as a PWA, so I might not complicate things too much just yet.

There's a chance I'll implement a few other emulators as time goes on, namely for skyemu, but the chances are pretty low outside of that since mGBA has pretty good support for the things I want without custom hardware.

**Comment by sonht0555** [comment]
I'm a designer, because I couldn't build Wasm myself, I tried to get those files from the developers when they uploaded them to the web view demo. A few times I asked them to help build, I did it all myself in terms of frontend, I like developing my own UI for GBA.

**Comment by sonht0555** [comment]
You must have seen my repo, this is my small product kabu.io.vn

**Comment by sonht0555** [comment]
mgba in this version is old, I am in the process of updating your core for it. I'm also looking forward to having two more features: support for Slang image filters and shaders like this
[https://youtube.com/@RetroCrisis?si=GeWW1u0Nr-OSa1k3]()

and the feature of keeping fps intact when in save battery mode of IOS. Usually, every time that mode is turned on, the game drops to 30fps. The VBA core I'm using can achieve it, but no one else can do it with mgba. I also talked to Sky, but asking him to build an mGBA wasm version like yours is a bit difficult, he doesn't have time to create all the modules like you did. Endrift is more comfortable, he also helped me build mGBA a few times

**Comment by sonht0555** [comment]
SkyEmu is doing a great job of keeping FPS and audio at 60fps when iOS is on battery save model and pixels on the canvas don't break when scaling to all resolutions. I really like this core. But Sky is packaging it into a large emulator, not dividing it into small features to use on the frontend to control. Because I understand, C is very difficult to edit or build
